//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.05 at 01:51:30 PM COT 
//


package co.nequi.message.integration.services.updatepromotionrule;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.nequi.message.integration.services.updatepromotionrule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdatePromotionRuleResponse_QNAME = new QName("http://nequi.co/message/integration/services/UpdatePromotionRule", "UpdatePromotionRuleResponse");
    private final static QName _UpdatePromotionRuleRequest_QNAME = new QName("http://nequi.co/message/integration/services/UpdatePromotionRule", "UpdatePromotionRuleRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.nequi.message.integration.services.updatepromotionrule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdatePromotionRuleRequestType }
     * 
     */
    public UpdatePromotionRuleRequestType createUpdatePromotionRuleRequestType() {
        return new UpdatePromotionRuleRequestType();
    }

    /**
     * Create an instance of {@link UpdatePromotionRuleResponseType }
     * 
     */
    public UpdatePromotionRuleResponseType createUpdatePromotionRuleResponseType() {
        return new UpdatePromotionRuleResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePromotionRuleResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/integration/services/UpdatePromotionRule", name = "UpdatePromotionRuleResponse")
    public JAXBElement<UpdatePromotionRuleResponseType> createUpdatePromotionRuleResponse(UpdatePromotionRuleResponseType value) {
        return new JAXBElement<UpdatePromotionRuleResponseType>(_UpdatePromotionRuleResponse_QNAME, UpdatePromotionRuleResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePromotionRuleRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/integration/services/UpdatePromotionRule", name = "UpdatePromotionRuleRequest")
    public JAXBElement<UpdatePromotionRuleRequestType> createUpdatePromotionRuleRequest(UpdatePromotionRuleRequestType value) {
        return new JAXBElement<UpdatePromotionRuleRequestType>(_UpdatePromotionRuleRequest_QNAME, UpdatePromotionRuleRequestType.class, null, value);
    }

}
