//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 07:42:41 AM COT 
//


package co.bdigital.admin.messaging.services.bco.acs502;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bcoBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bcoBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.grupobancolombia.com/BandaDigital/services/Backout/CloseAccount}CloseAccountServiceRequest"/>
 *         &lt;element ref="{http://www.grupobancolombia.com/BandaDigital/services/Backout/CompensatePhoneNumber}CompensatePhoneNumberServiceRequest"/>
 *         &lt;element ref="{http://www.grupobancolombia.com/BandaDigital/services/Backout/MassiveCloseAccount}MassiveCloseAccountServiceRequest"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bcoBodyType", propOrder = {
    "closeAccountServiceRequest",
    "compensatePhoneNumberServiceRequest",
    "massiveCloseAccountServiceRequest"
})
public class BcoBodyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CloseAccountServiceRequest", namespace = "http://www.grupobancolombia.com/BandaDigital/services/Backout/CloseAccount")
    protected CloseAccountServiceRequestType closeAccountServiceRequest;
    @XmlElement(name = "CompensatePhoneNumberServiceRequest", namespace = "http://www.grupobancolombia.com/BandaDigital/services/Backout/CompensatePhoneNumber")
    protected CompensatePhoneNumberServiceRequestType compensatePhoneNumberServiceRequest;
    @XmlElement(name = "MassiveCloseAccountServiceRequest", namespace = "http://www.grupobancolombia.com/BandaDigital/services/Backout/MassiveCloseAccount")
    protected MassiveCloseAccountServiceRequestType massiveCloseAccountServiceRequest;

    /**
     * Gets the value of the closeAccountServiceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CloseAccountServiceRequestType }
     *     
     */
    public CloseAccountServiceRequestType getCloseAccountServiceRequest() {
        return closeAccountServiceRequest;
    }

    /**
     * Sets the value of the closeAccountServiceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseAccountServiceRequestType }
     *     
     */
    public void setCloseAccountServiceRequest(CloseAccountServiceRequestType value) {
        this.closeAccountServiceRequest = value;
    }

    /**
     * Gets the value of the compensatePhoneNumberServiceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CompensatePhoneNumberServiceRequestType }
     *     
     */
    public CompensatePhoneNumberServiceRequestType getCompensatePhoneNumberServiceRequest() {
        return compensatePhoneNumberServiceRequest;
    }

    /**
     * Sets the value of the compensatePhoneNumberServiceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensatePhoneNumberServiceRequestType }
     *     
     */
    public void setCompensatePhoneNumberServiceRequest(CompensatePhoneNumberServiceRequestType value) {
        this.compensatePhoneNumberServiceRequest = value;
    }

    /**
     * Gets the value of the massiveCloseAccountServiceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link MassiveCloseAccountServiceRequestType }
     *     
     */
    public MassiveCloseAccountServiceRequestType getMassiveCloseAccountServiceRequest() {
        return massiveCloseAccountServiceRequest;
    }

    /**
     * Sets the value of the massiveCloseAccountServiceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassiveCloseAccountServiceRequestType }
     *     
     */
    public void setMassiveCloseAccountServiceRequest(MassiveCloseAccountServiceRequestType value) {
        this.massiveCloseAccountServiceRequest = value;
    }

}
