//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 07:42:41 AM COT 
//


package co.bdigital.admin.messaging.services.bco.acs502;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompensatePhoneNumberServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompensatePhoneNumberServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="compensatePhoneNumberRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/Backout/CompensatePhoneNumber}CompensatePhoneNumberRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompensatePhoneNumberServiceRequestType", namespace = "http://www.grupobancolombia.com/BandaDigital/services/Backout/CompensatePhoneNumber", propOrder = {
    "compensatePhoneNumberRQ"
})
public class CompensatePhoneNumberServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CompensatePhoneNumberRQType compensatePhoneNumberRQ;

    /**
     * Gets the value of the compensatePhoneNumberRQ property.
     * 
     * @return
     *     possible object is
     *     {@link CompensatePhoneNumberRQType }
     *     
     */
    public CompensatePhoneNumberRQType getCompensatePhoneNumberRQ() {
        return compensatePhoneNumberRQ;
    }

    /**
     * Sets the value of the compensatePhoneNumberRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensatePhoneNumberRQType }
     *     
     */
    public void setCompensatePhoneNumberRQ(CompensatePhoneNumberRQType value) {
        this.compensatePhoneNumberRQ = value;
    }

}
