//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 07:42:41 AM COT 
//


package co.bdigital.admin.messaging.services.bco.acs502;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MassiveCloseAccountRQType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MassiveCloseAccountRQType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountDetails" type="{http://www.grupobancolombia.com/BandaDigital/services/Backout/MassiveCloseAccount}AccountType"/>
 *         &lt;element name="emailToNotify" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MassiveCloseAccountRQType", namespace = "http://www.grupobancolombia.com/BandaDigital/services/Backout/MassiveCloseAccount", propOrder = {
    "accountDetails",
    "emailToNotify"
})
public class MassiveCloseAccountRQType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected AccountType accountDetails;
    @XmlElement(required = true)
    protected String emailToNotify;

    /**
     * Gets the value of the accountDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getAccountDetails() {
        return accountDetails;
    }

    /**
     * Sets the value of the accountDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setAccountDetails(AccountType value) {
        this.accountDetails = value;
    }

    /**
     * Gets the value of the emailToNotify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailToNotify() {
        return emailToNotify;
    }

    /**
     * Sets the value of the emailToNotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailToNotify(String value) {
        this.emailToNotify = value;
    }

}
