//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 10:13:36 AM COT 
//

package co.nequi.message.integration.services;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import co.bdigital.admin.messaging.services.getrulesdescription.GetRulesDescriptionRequestType;
import co.nequi.message.integration.services.addpromotionaudit.AddPromotionAuditRequestType;
import co.nequi.message.integration.services.getpromotiondetail.GetPromotionDetailRequestType;
import co.nequi.message.integration.services.updatepromotionrule.UpdatePromotionRuleRequestType;

/**
 * <p>
 * Java class for RequestBodyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RequestBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://nequi.co/message/integration/services/UpdatePromotionRule}UpdatePromotionRuleRequest"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/GetPromotionDetail}getPromotionDetailRequest"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/AddPromotionAudit}addPromotionAuditRequest"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/GetRulesDescription}getRulesDescriptionRequest"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestBodyType", propOrder = { "updatePromotionRuleRequest",
        "getPromotionDetailRequest", "addPromotionAuditRequest",
        "getRulesDescriptionRequest" })
public class RequestBodyType implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "UpdatePromotionRuleRequest", namespace = "http://nequi.co/message/integration/services/UpdatePromotionRule")
    protected UpdatePromotionRuleRequestType updatePromotionRuleRequest;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/GetPromotionDetail")
    protected GetPromotionDetailRequestType getPromotionDetailRequest;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/AddPromotionAudit")
    protected AddPromotionAuditRequestType addPromotionAuditRequest;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/GetRulesDescription")
    protected GetRulesDescriptionRequestType getRulesDescriptionRequest;

    /**
     * Gets the value of the updatePromotionRuleRequest property.
     * 
     * @return possible object is {@link UpdatePromotionRuleRequestType }
     * 
     */
    public UpdatePromotionRuleRequestType getUpdatePromotionRuleRequest() {
        return updatePromotionRuleRequest;
    }

    /**
     * Sets the value of the updatePromotionRuleRequest property.
     * 
     * @param value
     *            allowed object is {@link UpdatePromotionRuleRequestType }
     * 
     */
    public void setUpdatePromotionRuleRequest(
            UpdatePromotionRuleRequestType value) {
        this.updatePromotionRuleRequest = value;
    }

    /**
     * Gets the value of the getPromotionDetailRequest property.
     * 
     * @return possible object is {@link GetPromotionDetailRequestType }
     * 
     */
    public GetPromotionDetailRequestType getGetPromotionDetailRequest() {
        return getPromotionDetailRequest;
    }

    /**
     * Sets the value of the getPromotionDetailRequest property.
     * 
     * @param value
     *            allowed object is {@link GetPromotionDetailRequestType }
     * 
     */
    public void setGetPromotionDetailRequest(
            GetPromotionDetailRequestType value) {
        this.getPromotionDetailRequest = value;
    }

    /**
     * Gets the value of the addPromotionAuditRequest property.
     * 
     * @return possible object is {@link AddPromotionAuditRequestType }
     * 
     */
    public AddPromotionAuditRequestType getAddPromotionAuditRequest() {
        return addPromotionAuditRequest;
    }

    /**
     * Sets the value of the addPromotionAuditRequest property.
     * 
     * @param value
     *            allowed object is {@link AddPromotionAuditRequestType }
     * 
     */
    public void setAddPromotionAuditRequest(
            AddPromotionAuditRequestType value) {
        this.addPromotionAuditRequest = value;
    }

    /**
     * Gets the value of the getRulesDescriptionRequest property.
     * 
     * @return possible object is {@link GetRulesDescriptionRequestType }
     * 
     */
    public GetRulesDescriptionRequestType getGetRulesDescriptionRequest() {
        return getRulesDescriptionRequest;
    }

    /**
     * Sets the value of the getRulesDescriptionRequest property.
     * 
     * @param value
     *            allowed object is {@link GetRulesDescriptionRequestType }
     * 
     */
    public void setGetRulesDescriptionRequest(
            GetRulesDescriptionRequestType value) {
        this.getRulesDescriptionRequest = value;
    }

}
