//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.25 at 10:13:36 AM COT 
//

package co.nequi.message.integration.services;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import co.bdigital.admin.messaging.services.getrulesdescription.GetRulesDescriptionResponseType;
import co.nequi.message.integration.services.addpromotionaudit.AddPromotionAuditResponseType;
import co.nequi.message.integration.services.getpromotiondetail.GetPromotionDetailResponseType;
import co.nequi.message.integration.services.updatepromotionrule.UpdatePromotionRuleResponseType;

/**
 * <p>
 * Java class for ResponseBodyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://nequi.co/message/integration/services/UpdatePromotionRule}UpdatePromotionRuleResponse"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/GetPromotionDetail}getPromotionDetailResponse"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/AddPromotionAudit}addPromotionAuditResponse"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/GetRulesDescription}getRulesDescriptionResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseBodyType", propOrder = { "updatePromotionRuleResponse",
        "getPromotionDetailResponse", "addPromotionAuditResponse",
        "getRulesDescriptionResponse" })
public class ResponseBodyType implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "UpdatePromotionRuleResponse", namespace = "http://nequi.co/message/integration/services/UpdatePromotionRule")
    protected UpdatePromotionRuleResponseType updatePromotionRuleResponse;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/GetPromotionDetail")
    protected GetPromotionDetailResponseType getPromotionDetailResponse;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/AddPromotionAudit")
    protected AddPromotionAuditResponseType addPromotionAuditResponse;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/GetRulesDescription")
    protected GetRulesDescriptionResponseType getRulesDescriptionResponse;

    /**
     * Gets the value of the updatePromotionRuleResponse property.
     * 
     * @return possible object is {@link UpdatePromotionRuleResponseType }
     * 
     */
    public UpdatePromotionRuleResponseType getUpdatePromotionRuleResponse() {
        return updatePromotionRuleResponse;
    }

    /**
     * Sets the value of the updatePromotionRuleResponse property.
     * 
     * @param value
     *            allowed object is {@link UpdatePromotionRuleResponseType }
     * 
     */
    public void setUpdatePromotionRuleResponse(
            UpdatePromotionRuleResponseType value) {
        this.updatePromotionRuleResponse = value;
    }

    /**
     * Gets the value of the getPromotionDetailResponse property.
     * 
     * @return possible object is {@link GetPromotionDetailResponseType }
     * 
     */
    public GetPromotionDetailResponseType getGetPromotionDetailResponse() {
        return getPromotionDetailResponse;
    }

    /**
     * Sets the value of the getPromotionDetailResponse property.
     * 
     * @param value
     *            allowed object is {@link GetPromotionDetailResponseType }
     * 
     */
    public void setGetPromotionDetailResponse(
            GetPromotionDetailResponseType value) {
        this.getPromotionDetailResponse = value;
    }

    /**
     * Gets the value of the addPromotionAuditResponse property.
     * 
     * @return possible object is {@link AddPromotionAuditResponseType }
     * 
     */
    public AddPromotionAuditResponseType getAddPromotionAuditResponse() {
        return addPromotionAuditResponse;
    }

    /**
     * Sets the value of the addPromotionAuditResponse property.
     * 
     * @param value
     *            allowed object is {@link AddPromotionAuditResponseType }
     * 
     */
    public void setAddPromotionAuditResponse(
            AddPromotionAuditResponseType value) {
        this.addPromotionAuditResponse = value;
    }

    /**
     * Gets the value of the getRulesDescriptionResponse property.
     * 
     * @return possible object is {@link GetRulesDescriptionResponseType }
     * 
     */
    public GetRulesDescriptionResponseType getGetRulesDescriptionResponse() {
        return getRulesDescriptionResponse;
    }

    /**
     * Sets the value of the getRulesDescriptionResponse property.
     * 
     * @param value
     *            allowed object is {@link GetRulesDescriptionResponseType }
     * 
     */
    public void setGetRulesDescriptionResponse(
            GetRulesDescriptionResponseType value) {
        this.getRulesDescriptionResponse = value;
    }

}
