//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:33 AM COT 
//


package co.bdigital.admin.messaging.services.biometric.updateProfile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.biometric.updateProfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateProfileDaonServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/UpdateProfile", "UpdateProfileDaonServiceRequest");
    private final static QName _UpdateProfileDaonServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/UpdateProfile", "UpdateProfileDaonServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.biometric.updateProfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateProfileDaonServiceResponseType }
     * 
     */
    public UpdateProfileDaonServiceResponseType createUpdateProfileDaonServiceResponseType() {
        return new UpdateProfileDaonServiceResponseType();
    }

    /**
     * Create an instance of {@link UpdateProfileDaonServiceRequestType }
     * 
     */
    public UpdateProfileDaonServiceRequestType createUpdateProfileDaonServiceRequestType() {
        return new UpdateProfileDaonServiceRequestType();
    }

    /**
     * Create an instance of {@link FaceDataType }
     * 
     */
    public FaceDataType createFaceDataType() {
        return new FaceDataType();
    }

    /**
     * Create an instance of {@link UpdateProfileDaonRQType }
     * 
     */
    public UpdateProfileDaonRQType createUpdateProfileDaonRQType() {
        return new UpdateProfileDaonRQType();
    }

    /**
     * Create an instance of {@link VoiceDataType }
     * 
     */
    public VoiceDataType createVoiceDataType() {
        return new VoiceDataType();
    }

    /**
     * Create an instance of {@link UpdateProfileDaonRSType }
     * 
     */
    public UpdateProfileDaonRSType createUpdateProfileDaonRSType() {
        return new UpdateProfileDaonRSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProfileDaonServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/UpdateProfile", name = "UpdateProfileDaonServiceRequest")
    public JAXBElement<UpdateProfileDaonServiceRequestType> createUpdateProfileDaonServiceRequest(UpdateProfileDaonServiceRequestType value) {
        return new JAXBElement<UpdateProfileDaonServiceRequestType>(_UpdateProfileDaonServiceRequest_QNAME, UpdateProfileDaonServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProfileDaonServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/UpdateProfile", name = "UpdateProfileDaonServiceResponse")
    public JAXBElement<UpdateProfileDaonServiceResponseType> createUpdateProfileDaonServiceResponse(UpdateProfileDaonServiceResponseType value) {
        return new JAXBElement<UpdateProfileDaonServiceResponseType>(_UpdateProfileDaonServiceResponse_QNAME, UpdateProfileDaonServiceResponseType.class, null, value);
    }

}
