//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 10:09:33 AM COT 
//

package co.bdigital.admin.messaging.services.biometric.updateProfile;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for UpdateProfileDaonRQType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateProfileDaonRQType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flagCreate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="softToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="faceData" type="{http://www.grupobancolombia.com/BandaDigital/services/UpdateProfile}FaceDataType" minOccurs="0"/>
 *         &lt;element name="voiceData" type="{http://www.grupobancolombia.com/BandaDigital/services/UpdateProfile}VoiceDataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="versionSO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sistemaOperativo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateProfileDaonRQType", propOrder = { "phoneNumber",
        "action", "uuid", "flagCreate", "softToken", "faceData", "voiceData",
        "model", "manufacturer", "versionSO", "sistemaOperativo" })
public class UpdateProfileDaonRQType implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String phoneNumber;
    @XmlElement(required = true)
    protected String action;
    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String flagCreate;
    @XmlElement(required = true)
    protected String softToken;
    protected FaceDataType faceData;
    protected List<VoiceDataType> voiceData;
    protected String model;
    protected String manufacturer;
    @XmlElement(required = true)
    protected String versionSO;
    @XmlElement(required = true)
    protected String sistemaOperativo;

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the flagCreate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFlagCreate() {
        return flagCreate;
    }

    /**
     * Sets the value of the flagCreate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFlagCreate(String value) {
        this.flagCreate = value;
    }

    /**
     * Gets the value of the softToken property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSoftToken() {
        return softToken;
    }

    /**
     * Sets the value of the softToken property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSoftToken(String value) {
        this.softToken = value;
    }

    /**
     * Gets the value of the faceData property.
     * 
     * @return possible object is {@link FaceDataType }
     * 
     */
    public FaceDataType getFaceData() {
        return faceData;
    }

    /**
     * Sets the value of the faceData property.
     * 
     * @param value
     *            allowed object is {@link FaceDataType }
     * 
     */
    public void setFaceData(FaceDataType value) {
        this.faceData = value;
    }

    /**
     * Gets the value of the voiceData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the voiceData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getVoiceData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VoiceDataType }
     * 
     * 
     */
    public List<VoiceDataType> getVoiceData() {
        if (voiceData == null) {
            voiceData = new ArrayList<VoiceDataType>();
        }
        return this.voiceData;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the versionSO property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersionSO() {
        return versionSO;
    }

    /**
     * Sets the value of the versionSO property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersionSO(String value) {
        this.versionSO = value;
    }

    /**
     * Gets the value of the sistemaOperativo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSistemaOperativo() {
        return sistemaOperativo;
    }

    /**
     * Sets the value of the sistemaOperativo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSistemaOperativo(String value) {
        this.sistemaOperativo = value;
    }

    /**
     * @param voiceData
     *            the voiceData to set
     */
    public void setVoiceData(List<VoiceDataType> voiceData) {
        this.voiceData = voiceData;
    }

}
