//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 10:09:55 AM COT 
//


package co.bdigital.admin.messaging.services.customerLockManagment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.customerLockManagment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerLockManagmentServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/UserServices", "CustomerLockManagmentServiceResponse");
    private final static QName _CustomerLockManagmentServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/UserServices", "CustomerLockManagmentServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.customerLockManagment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerLockManagmentServiceResponseType }
     * 
     */
    public CustomerLockManagmentServiceResponseType createCustomerLockManagmentServiceResponseType() {
        return new CustomerLockManagmentServiceResponseType();
    }

    /**
     * Create an instance of {@link CustomerLockManagmentServiceRequestType }
     * 
     */
    public CustomerLockManagmentServiceRequestType createCustomerLockManagmentServiceRequestType() {
        return new CustomerLockManagmentServiceRequestType();
    }

    /**
     * Create an instance of {@link CustomerLockManagmentRSType }
     * 
     */
    public CustomerLockManagmentRSType createCustomerLockManagmentRSType() {
        return new CustomerLockManagmentRSType();
    }

    /**
     * Create an instance of {@link CustomerLockManagmentRQType }
     * 
     */
    public CustomerLockManagmentRQType createCustomerLockManagmentRQType() {
        return new CustomerLockManagmentRQType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerLockManagmentServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/UserServices", name = "CustomerLockManagmentServiceResponse")
    public JAXBElement<CustomerLockManagmentServiceResponseType> createCustomerLockManagmentServiceResponse(CustomerLockManagmentServiceResponseType value) {
        return new JAXBElement<CustomerLockManagmentServiceResponseType>(_CustomerLockManagmentServiceResponse_QNAME, CustomerLockManagmentServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerLockManagmentServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/UserServices", name = "CustomerLockManagmentServiceRequest")
    public JAXBElement<CustomerLockManagmentServiceRequestType> createCustomerLockManagmentServiceRequest(CustomerLockManagmentServiceRequestType value) {
        return new JAXBElement<CustomerLockManagmentServiceRequestType>(_CustomerLockManagmentServiceRequest_QNAME, CustomerLockManagmentServiceRequestType.class, null, value);
    }

}
