//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.11 at 09:58:50 AM COT 
//


package co.bdigital.admin.messaging.integration.ldap401.v100;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestBodyObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestBodyObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://nequi.co/message/integration/services/UpdateUserLDAPServices}UpdateUserLDAPServiceRequest"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/DeleteUserLDAPServices}DeleteUserLDAPServiceRequest"/>
 *         &lt;element ref="{http://nequi.co/message/integration/services/CreateUserLDAPServices}CreateUserLDAPServiceRequest"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestBodyObjectType", propOrder = {
    "updateUserLDAPServiceRequest",
    "deleteUserLDAPServiceRequest",
    "createUserLDAPServiceRequest"
})
public class RequestBodyObjectType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "UpdateUserLDAPServiceRequest", namespace = "http://nequi.co/message/integration/services/UpdateUserLDAPServices")
    protected UpdateUserLDAPServiceRequestType updateUserLDAPServiceRequest;
    @XmlElement(name = "DeleteUserLDAPServiceRequest", namespace = "http://nequi.co/message/integration/services/DeleteUserLDAPServices")
    protected DeleteUserLDAPServiceRequestType deleteUserLDAPServiceRequest;
    @XmlElement(name = "CreateUserLDAPServiceRequest", namespace = "http://nequi.co/message/integration/services/CreateUserLDAPServices")
    protected CreateUserLDAPServiceRequestType createUserLDAPServiceRequest;

    /**
     * Gets the value of the updateUserLDAPServiceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateUserLDAPServiceRequestType }
     *     
     */
    public UpdateUserLDAPServiceRequestType getUpdateUserLDAPServiceRequest() {
        return updateUserLDAPServiceRequest;
    }

    /**
     * Sets the value of the updateUserLDAPServiceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateUserLDAPServiceRequestType }
     *     
     */
    public void setUpdateUserLDAPServiceRequest(UpdateUserLDAPServiceRequestType value) {
        this.updateUserLDAPServiceRequest = value;
    }

    /**
     * Gets the value of the deleteUserLDAPServiceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteUserLDAPServiceRequestType }
     *     
     */
    public DeleteUserLDAPServiceRequestType getDeleteUserLDAPServiceRequest() {
        return deleteUserLDAPServiceRequest;
    }

    /**
     * Sets the value of the deleteUserLDAPServiceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteUserLDAPServiceRequestType }
     *     
     */
    public void setDeleteUserLDAPServiceRequest(DeleteUserLDAPServiceRequestType value) {
        this.deleteUserLDAPServiceRequest = value;
    }

    /**
     * Gets the value of the createUserLDAPServiceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CreateUserLDAPServiceRequestType }
     *     
     */
    public CreateUserLDAPServiceRequestType getCreateUserLDAPServiceRequest() {
        return createUserLDAPServiceRequest;
    }

    /**
     * Sets the value of the createUserLDAPServiceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateUserLDAPServiceRequestType }
     *     
     */
    public void setCreateUserLDAPServiceRequest(CreateUserLDAPServiceRequestType value) {
        this.createUserLDAPServiceRequest = value;
    }

}
