//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.11 at 09:58:50 AM COT 
//


package co.bdigital.admin.messaging.integration.ldap401.v100;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateUserLDAPServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateUserLDAPServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="changeInfoLoginRQ" type="{http://nequi.co/message/integration/services/UpdateUserLDAPServices}ChangeInfoLoginRQType"/>
 *         &lt;element name="changePasswordRQ" type="{http://nequi.co/message/integration/services/UpdateUserLDAPServices}ChangePasswordRQType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateUserLDAPServiceRequestType", namespace = "http://nequi.co/message/integration/services/UpdateUserLDAPServices", propOrder = {
    "changeInfoLoginRQ",
    "changePasswordRQ"
})
public class UpdateUserLDAPServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected ChangeInfoLoginRQType changeInfoLoginRQ;
    protected ChangePasswordRQType changePasswordRQ;

    /**
     * Gets the value of the changeInfoLoginRQ property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeInfoLoginRQType }
     *     
     */
    public ChangeInfoLoginRQType getChangeInfoLoginRQ() {
        return changeInfoLoginRQ;
    }

    /**
     * Sets the value of the changeInfoLoginRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeInfoLoginRQType }
     *     
     */
    public void setChangeInfoLoginRQ(ChangeInfoLoginRQType value) {
        this.changeInfoLoginRQ = value;
    }

    /**
     * Gets the value of the changePasswordRQ property.
     * 
     * @return
     *     possible object is
     *     {@link ChangePasswordRQType }
     *     
     */
    public ChangePasswordRQType getChangePasswordRQ() {
        return changePasswordRQ;
    }

    /**
     * Sets the value of the changePasswordRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangePasswordRQType }
     *     
     */
    public void setChangePasswordRQ(ChangePasswordRQType value) {
        this.changePasswordRQ = value;
    }

}
