//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.25 at 05:18:50 PM COT 
//


package co.bdigital.admin.messaging.services.getcustomerlocks;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCustomerLocksServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCustomerLocksServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getCustomerLocksRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/GetCustomerLocksService}GetCustomerLocksRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCustomerLocksServiceRequestType", propOrder = {
    "getCustomerLocksRQ"
})
public class GetCustomerLocksServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected GetCustomerLocksRQType getCustomerLocksRQ;

    /**
     * Gets the value of the getCustomerLocksRQ property.
     * 
     * @return
     *     possible object is
     *     {@link GetCustomerLocksRQType }
     *     
     */
    public GetCustomerLocksRQType getGetCustomerLocksRQ() {
        return getCustomerLocksRQ;
    }

    /**
     * Sets the value of the getCustomerLocksRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCustomerLocksRQType }
     *     
     */
    public void setGetCustomerLocksRQ(GetCustomerLocksRQType value) {
        this.getCustomerLocksRQ = value;
    }

}
