//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.31 at 05:21:36 PM COT 
//


package co.bdigital.admin.messaging.services.getcustomerdetails;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCustomerStatusResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCustomerStatusResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getCustomerStatusRS" type="{http://www.grupobancolombia.com/BandaDigital/services/ResetPasswordServices}GetCustomerStatusRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCustomerStatusResponseType", propOrder = {
    "getCustomerStatusRS"
})
public class GetCustomerStatusResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected GetCustomerStatusRSType getCustomerStatusRS;

    /**
     * Gets the value of the getCustomerStatusRS property.
     * 
     * @return
     *     possible object is
     *     {@link GetCustomerStatusRSType }
     *     
     */
    public GetCustomerStatusRSType getGetCustomerStatusRS() {
        return getCustomerStatusRS;
    }

    /**
     * Sets the value of the getCustomerStatusRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCustomerStatusRSType }
     *     
     */
    public void setGetCustomerStatusRS(GetCustomerStatusRSType value) {
        this.getCustomerStatusRS = value;
    }

}
