//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 10:04:22 AM COT 
//


package co.bdigital.admin.messaging.closeaccount;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CloseAccountServiceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CloseAccountServiceResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="closeAccountRS" type="{http://www.grupobancolombia.com/BandaDigital/services/AccountServices}CloseAccountRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CloseAccountServiceResponseType", propOrder = {
    "closeAccountRS"
})
public class CloseAccountServiceResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CloseAccountRSType closeAccountRS;

    /**
     * Gets the value of the closeAccountRS property.
     * 
     * @return
     *     possible object is
     *     {@link CloseAccountRSType }
     *     
     */
    public CloseAccountRSType getCloseAccountRS() {
        return closeAccountRS;
    }

    /**
     * Sets the value of the closeAccountRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseAccountRSType }
     *     
     */
    public void setCloseAccountRS(CloseAccountRSType value) {
        this.closeAccountRS = value;
    }

}
