//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 10:04:22 AM COT 
//


package co.bdigital.admin.messaging.closeaccount;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CloseAccountServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CloseAccountServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="closeAccountRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/AccountServices}CloseAccountRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CloseAccountServiceRequestType", propOrder = {
    "closeAccountRQ"
})
public class CloseAccountServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CloseAccountRQType closeAccountRQ;

    /**
     * Gets the value of the closeAccountRQ property.
     * 
     * @return
     *     possible object is
     *     {@link CloseAccountRQType }
     *     
     */
    public CloseAccountRQType getCloseAccountRQ() {
        return closeAccountRQ;
    }

    /**
     * Sets the value of the closeAccountRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloseAccountRQType }
     *     
     */
    public void setCloseAccountRQ(CloseAccountRQType value) {
        this.closeAccountRQ = value;
    }

}
