//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.09 at 10:04:22 AM COT 
//


package co.bdigital.admin.messaging.closeaccount;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.closeaccount package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CloseAccountServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/AccountServices", "CloseAccountServiceRequest");
    private final static QName _CloseAccountServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/AccountServices", "CloseAccountServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.closeaccount
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CloseAccountServiceResponseType }
     * 
     */
    public CloseAccountServiceResponseType createCloseAccountServiceResponseType() {
        return new CloseAccountServiceResponseType();
    }

    /**
     * Create an instance of {@link CloseAccountServiceRequestType }
     * 
     */
    public CloseAccountServiceRequestType createCloseAccountServiceRequestType() {
        return new CloseAccountServiceRequestType();
    }

    /**
     * Create an instance of {@link CloseAccountRQType }
     * 
     */
    public CloseAccountRQType createCloseAccountRQType() {
        return new CloseAccountRQType();
    }

    /**
     * Create an instance of {@link CloseAccountRSType }
     * 
     */
    public CloseAccountRSType createCloseAccountRSType() {
        return new CloseAccountRSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseAccountServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/AccountServices", name = "CloseAccountServiceRequest")
    public JAXBElement<CloseAccountServiceRequestType> createCloseAccountServiceRequest(CloseAccountServiceRequestType value) {
        return new JAXBElement<CloseAccountServiceRequestType>(_CloseAccountServiceRequest_QNAME, CloseAccountServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseAccountServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/AccountServices", name = "CloseAccountServiceResponse")
    public JAXBElement<CloseAccountServiceResponseType> createCloseAccountServiceResponse(CloseAccountServiceResponseType value) {
        return new JAXBElement<CloseAccountServiceResponseType>(_CloseAccountServiceResponse_QNAME, CloseAccountServiceResponseType.class, null, value);
    }

}
