//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.07 at 09:01:58 AM COT 
//


package co.bdigital.admin.messaging.services.blockClient;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BlockClientServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlockClientServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="blockClientRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/BlockClientServices}BlockClientRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlockClientServiceRequestType", propOrder = {
    "blockClientRQ"
})
public class BlockClientServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected BlockClientRQType blockClientRQ;

    /**
     * Gets the value of the blockClientRQ property.
     * 
     * @return
     *     possible object is
     *     {@link BlockClientRQType }
     *     
     */
    public BlockClientRQType getBlockClientRQ() {
        return blockClientRQ;
    }

    /**
     * Sets the value of the blockClientRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockClientRQType }
     *     
     */
    public void setBlockClientRQ(BlockClientRQType value) {
        this.blockClientRQ = value;
    }

}
