//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 02:57:52 PM COT 
//


package co.bdigital.admin.messaging.services.getrulesdescription;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.getrulesdescription package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetRulesDescriptionRequest_QNAME = new QName("http://nequi.co/message/integration/services/GetRulesDescription", "getRulesDescriptionRequest");
    private final static QName _GetRulesDescriptionResponse_QNAME = new QName("http://nequi.co/message/integration/services/GetRulesDescription", "getRulesDescriptionResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.getrulesdescription
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRulesDescriptionRequestType }
     * 
     */
    public GetRulesDescriptionRequestType createGetRulesDescriptionRequestType() {
        return new GetRulesDescriptionRequestType();
    }

    /**
     * Create an instance of {@link GetRulesDescriptionResponseType }
     * 
     */
    public GetRulesDescriptionResponseType createGetRulesDescriptionResponseType() {
        return new GetRulesDescriptionResponseType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRulesDescriptionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/integration/services/GetRulesDescription", name = "getRulesDescriptionRequest")
    public JAXBElement<GetRulesDescriptionRequestType> createGetRulesDescriptionRequest(GetRulesDescriptionRequestType value) {
        return new JAXBElement<GetRulesDescriptionRequestType>(_GetRulesDescriptionRequest_QNAME, GetRulesDescriptionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRulesDescriptionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/integration/services/GetRulesDescription", name = "getRulesDescriptionResponse")
    public JAXBElement<GetRulesDescriptionResponseType> createGetRulesDescriptionResponse(GetRulesDescriptionResponseType value) {
        return new JAXBElement<GetRulesDescriptionResponseType>(_GetRulesDescriptionResponse_QNAME, GetRulesDescriptionResponseType.class, null, value);
    }

}
