//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 02:57:52 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/message/integration/services/GetRulesDescription", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.bdigital.admin.messaging.services.getrulesdescription;
