//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:42 AM COT 
//


package co.bdigital.admin.messaging.services.biometric.getProfileById;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetProfileByIDRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProfileByIDRSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profileUniqueIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profileIID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isFaceEnrolled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isVoiceEnrolled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enrollmentDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isProfileBlocked" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="face" type="{http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices}FaceType" minOccurs="0"/>
 *         &lt;element name="voice" type="{http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices}VoiceType" minOccurs="0"/>
 *         &lt;element name="palm" type="{http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices}PalmType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProfileByIDRSType", propOrder = {
    "profileUniqueIdentifier",
    "profileIID",
    "isFaceEnrolled",
    "isVoiceEnrolled",
    "enrollmentDateTime",
    "isProfileBlocked",
    "face",
    "voice",
    "palm"
})
public class GetProfileByIDRSType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String profileUniqueIdentifier;
    @XmlElement(required = true)
    protected String profileIID;
    @XmlElement(required = true)
    protected String isFaceEnrolled;
    @XmlElement(required = true)
    protected String isVoiceEnrolled;
    @XmlElement(required = true)
    protected String enrollmentDateTime;
    @XmlElement(required = true)
    protected String isProfileBlocked;
    protected FaceType face;
    protected VoiceType voice;
    protected PalmType palm;

    /**
     * Gets the value of the profileUniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileUniqueIdentifier() {
        return profileUniqueIdentifier;
    }

    /**
     * Sets the value of the profileUniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileUniqueIdentifier(String value) {
        this.profileUniqueIdentifier = value;
    }

    /**
     * Gets the value of the profileIID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileIID() {
        return profileIID;
    }

    /**
     * Sets the value of the profileIID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileIID(String value) {
        this.profileIID = value;
    }

    /**
     * Gets the value of the isFaceEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFaceEnrolled() {
        return isFaceEnrolled;
    }

    /**
     * Sets the value of the isFaceEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFaceEnrolled(String value) {
        this.isFaceEnrolled = value;
    }

    /**
     * Gets the value of the isVoiceEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsVoiceEnrolled() {
        return isVoiceEnrolled;
    }

    /**
     * Sets the value of the isVoiceEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsVoiceEnrolled(String value) {
        this.isVoiceEnrolled = value;
    }

    /**
     * Gets the value of the enrollmentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentDateTime() {
        return enrollmentDateTime;
    }

    /**
     * Sets the value of the enrollmentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentDateTime(String value) {
        this.enrollmentDateTime = value;
    }

    /**
     * Gets the value of the isProfileBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsProfileBlocked() {
        return isProfileBlocked;
    }

    /**
     * Sets the value of the isProfileBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsProfileBlocked(String value) {
        this.isProfileBlocked = value;
    }

    /**
     * Gets the value of the face property.
     * 
     * @return
     *     possible object is
     *     {@link FaceType }
     *     
     */
    public FaceType getFace() {
        return face;
    }

    /**
     * Sets the value of the face property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaceType }
     *     
     */
    public void setFace(FaceType value) {
        this.face = value;
    }

    /**
     * Gets the value of the voice property.
     * 
     * @return
     *     possible object is
     *     {@link VoiceType }
     *     
     */
    public VoiceType getVoice() {
        return voice;
    }

    /**
     * Sets the value of the voice property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoiceType }
     *     
     */
    public void setVoice(VoiceType value) {
        this.voice = value;
    }

    /**
     * Gets the value of the palm property.
     * 
     * @return
     *     possible object is
     *     {@link PalmType }
     *     
     */
    public PalmType getPalm() {
        return palm;
    }

    /**
     * Sets the value of the palm property.
     * 
     * @param value
     *     allowed object is
     *     {@link PalmType }
     *     
     */
    public void setPalm(PalmType value) {
        this.palm = value;
    }

}
