//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:42 AM COT 
//


package co.bdigital.admin.messaging.services.biometric.getProfileById;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.biometric.getProfileById package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetProfileByIDServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices", "GetProfileByIDServiceRequest");
    private final static QName _GetProfileByIDServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices", "GetProfileByIDServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.biometric.getProfileById
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProfileByIDServiceRequestType }
     * 
     */
    public GetProfileByIDServiceRequestType createGetProfileByIDServiceRequestType() {
        return new GetProfileByIDServiceRequestType();
    }

    /**
     * Create an instance of {@link GetProfileByIDServiceResponseType }
     * 
     */
    public GetProfileByIDServiceResponseType createGetProfileByIDServiceResponseType() {
        return new GetProfileByIDServiceResponseType();
    }

    /**
     * Create an instance of {@link GetProfileByIDRSType }
     * 
     */
    public GetProfileByIDRSType createGetProfileByIDRSType() {
        return new GetProfileByIDRSType();
    }

    /**
     * Create an instance of {@link GetProfileByIDRQType }
     * 
     */
    public GetProfileByIDRQType createGetProfileByIDRQType() {
        return new GetProfileByIDRQType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link VoiceType }
     * 
     */
    public VoiceType createVoiceType() {
        return new VoiceType();
    }

    /**
     * Create an instance of {@link FaceType }
     * 
     */
    public FaceType createFaceType() {
        return new FaceType();
    }

    /**
     * Create an instance of {@link PalmType }
     * 
     */
    public PalmType createPalmType() {
        return new PalmType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProfileByIDServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices", name = "GetProfileByIDServiceRequest")
    public JAXBElement<GetProfileByIDServiceRequestType> createGetProfileByIDServiceRequest(GetProfileByIDServiceRequestType value) {
        return new JAXBElement<GetProfileByIDServiceRequestType>(_GetProfileByIDServiceRequest_QNAME, GetProfileByIDServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProfileByIDServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/GetProfileByIDServices", name = "GetProfileByIDServiceResponse")
    public JAXBElement<GetProfileByIDServiceResponseType> createGetProfileByIDServiceResponse(GetProfileByIDServiceResponseType value) {
        return new JAXBElement<GetProfileByIDServiceResponseType>(_GetProfileByIDServiceResponse_QNAME, GetProfileByIDServiceResponseType.class, null, value);
    }

}
