//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:42 AM COT 
//


package co.bdigital.admin.messaging.services.biometric.getProfileById;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voiceFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="utterance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoiceType", propOrder = {
    "data",
    "voiceFormat",
    "utterance"
})
public class VoiceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String data;
    @XmlElement(required = true)
    protected String voiceFormat;
    @XmlElement(required = true)
    protected String utterance;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the voiceFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoiceFormat() {
        return voiceFormat;
    }

    /**
     * Sets the value of the voiceFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoiceFormat(String value) {
        this.voiceFormat = value;
    }

    /**
     * Gets the value of the utterance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtterance() {
        return utterance;
    }

    /**
     * Sets the value of the utterance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtterance(String value) {
        this.utterance = value;
    }

}
