//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.17 at 04:34:02 PM COT 
//


package co.bdigital.admin.messaging.services.getbiometryondemand;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetBiometryOnDemandServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBiometryOnDemandServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getBiometryOnDemandRQ" type="{http://www.example.org/SHP_MSG_GetBiometryOnDemandService}GetBiometryOnDemandRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBiometryOnDemandServiceRequestType", propOrder = {
    "getBiometryOnDemandRQ"
})
public class GetBiometryOnDemandServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected GetBiometryOnDemandRQType getBiometryOnDemandRQ;

    /**
     * Gets the value of the getBiometryOnDemandRQ property.
     * 
     * @return
     *     possible object is
     *     {@link GetBiometryOnDemandRQType }
     *     
     */
    public GetBiometryOnDemandRQType getGetBiometryOnDemandRQ() {
        return getBiometryOnDemandRQ;
    }

    /**
     * Sets the value of the getBiometryOnDemandRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetBiometryOnDemandRQType }
     *     
     */
    public void setGetBiometryOnDemandRQ(GetBiometryOnDemandRQType value) {
        this.getBiometryOnDemandRQ = value;
    }

}
