//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.17 at 04:34:02 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/SHP_MSG_GetBiometryOnDemandService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.bdigital.admin.messaging.services.getbiometryondemand;
