//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.01 at 01:39:54 PM COT 
//


package co.bdigital.admin.messaging.services.getVeriAttempts;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetVeriAttemptsServiceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetVeriAttemptsServiceResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getVeriAttemptsRS" type="{http://www.grupobancolombia.com/BandaDigital/services/GetVeriAttemptsServices}GetVeriAttemptsRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetVeriAttemptsServiceResponseType", propOrder = {
    "getVeriAttemptsRS"
})
public class GetVeriAttemptsServiceResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected GetVeriAttemptsRSType getVeriAttemptsRS;

    /**
     * Gets the value of the getVeriAttemptsRS property.
     * 
     * @return
     *     possible object is
     *     {@link GetVeriAttemptsRSType }
     *     
     */
    public GetVeriAttemptsRSType getGetVeriAttemptsRS() {
        return getVeriAttemptsRS;
    }

    /**
     * Sets the value of the getVeriAttemptsRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetVeriAttemptsRSType }
     *     
     */
    public void setGetVeriAttemptsRS(GetVeriAttemptsRSType value) {
        this.getVeriAttemptsRS = value;
    }

}
