//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.01 at 01:39:54 PM COT 
//


package co.bdigital.admin.messaging.services.getVeriAttempts;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetVeriAttemptsServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetVeriAttemptsServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getVeriAttemptsRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/GetVeriAttemptsServices}GetVeriAttemptsRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetVeriAttemptsServiceRequestType", propOrder = {
    "getVeriAttemptsRQ"
})
public class GetVeriAttemptsServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected GetVeriAttemptsRQType getVeriAttemptsRQ;

    /**
     * Gets the value of the getVeriAttemptsRQ property.
     * 
     * @return
     *     possible object is
     *     {@link GetVeriAttemptsRQType }
     *     
     */
    public GetVeriAttemptsRQType getGetVeriAttemptsRQ() {
        return getVeriAttemptsRQ;
    }

    /**
     * Sets the value of the getVeriAttemptsRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetVeriAttemptsRQType }
     *     
     */
    public void setGetVeriAttemptsRQ(GetVeriAttemptsRQType value) {
        this.getVeriAttemptsRQ = value;
    }

}
