//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.01 at 01:39:54 PM COT 
//


package co.bdigital.admin.messaging.services.getVeriAttempts;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetVeriAttemptsRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetVeriAttemptsRSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cifId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attempts" type="{http://www.grupobancolombia.com/BandaDigital/services/GetVeriAttemptsServices}AttemptsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetVeriAttemptsRSType", propOrder = {
    "cifId",
    "attempts"
})
public class GetVeriAttemptsRSType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String cifId;
    protected List<AttemptsType> attempts;

    /**
     * Gets the value of the cifId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCifId() {
        return cifId;
    }

    /**
     * Sets the value of the cifId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCifId(String value) {
        this.cifId = value;
    }

    /**
     * Gets the value of the attempts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attempts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttempts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttemptsType }
     * 
     * 
     */
    public List<AttemptsType> getAttempts() {
        if (attempts == null) {
            attempts = new ArrayList<AttemptsType>();
        }
        return this.attempts;
    }

}
