//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.11 at 04:58:00 PM COT 
//


package co.bdigital.admin.messaging.services.gmf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.gmf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseMessage_QNAME = new QName("http://nequi.co/message/bussines/services/", "responseMessage");
    private final static QName _OperationGMFRQ_QNAME = new QName("http://nequi.co/message/bussines/services/operation", "operationGMFRQ");
    private final static QName _OperationGMFRS_QNAME = new QName("http://nequi.co/message/bussines/services/operation", "operationGMFRS");
    private final static QName _RequestMessage_QNAME = new QName("http://nequi.co/message/bussines/services/", "requestMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.gmf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestMessageType }
     * 
     */
    public RequestMessageType createRequestMessageType() {
        return new RequestMessageType();
    }

    /**
     * Create an instance of {@link MessageRS }
     * 
     */
    public MessageRS createMessageRS() {
        return new MessageRS();
    }

    /**
     * Create an instance of {@link ResponseMessageType }
     * 
     */
    public ResponseMessageType createResponseMessageType() {
        return new ResponseMessageType();
    }

    /**
     * Create an instance of {@link MessageRQ }
     * 
     */
    public MessageRQ createMessageRQ() {
        return new MessageRQ();
    }

    /**
     * Create an instance of {@link MessageRQType }
     * 
     */
    public MessageRQType createMessageRQType() {
        return new MessageRQType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link RequestBodyType }
     * 
     */
    public RequestBodyType createRequestBodyType() {
        return new RequestBodyType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link ResponseBodyType }
     * 
     */
    public ResponseBodyType createResponseBodyType() {
        return new ResponseBodyType();
    }

    /**
     * Create an instance of {@link ChannelType }
     * 
     */
    public ChannelType createChannelType() {
        return new ChannelType();
    }

    /**
     * Create an instance of {@link RequestHeaderType }
     * 
     */
    public RequestHeaderType createRequestHeaderType() {
        return new RequestHeaderType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link ConsumerType }
     * 
     */
    public ConsumerType createConsumerType() {
        return new ConsumerType();
    }

    /**
     * Create an instance of {@link SecurityType }
     * 
     */
    public SecurityType createSecurityType() {
        return new SecurityType();
    }

    /**
     * Create an instance of {@link ResponseHeaderType }
     * 
     */
    public ResponseHeaderType createResponseHeaderType() {
        return new ResponseHeaderType();
    }

    /**
     * Create an instance of {@link DestinationType }
     * 
     */
    public DestinationType createDestinationType() {
        return new DestinationType();
    }

    /**
     * Create an instance of {@link MessageRSType }
     * 
     */
    public MessageRSType createMessageRSType() {
        return new MessageRSType();
    }

    /**
     * Create an instance of {@link OperationGMFRSType }
     * 
     */
    public OperationGMFRSType createOperationGMFRSType() {
        return new OperationGMFRSType();
    }

    /**
     * Create an instance of {@link OperationGMFRQType }
     * 
     */
    public OperationGMFRQType createOperationGMFRQType() {
        return new OperationGMFRQType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/bussines/services/", name = "responseMessage")
    public JAXBElement<ResponseMessageType> createResponseMessage(ResponseMessageType value) {
        return new JAXBElement<ResponseMessageType>(_ResponseMessage_QNAME, ResponseMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationGMFRQType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/bussines/services/operation", name = "operationGMFRQ")
    public JAXBElement<OperationGMFRQType> createOperationGMFRQ(OperationGMFRQType value) {
        return new JAXBElement<OperationGMFRQType>(_OperationGMFRQ_QNAME, OperationGMFRQType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationGMFRSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/bussines/services/operation", name = "operationGMFRS")
    public JAXBElement<OperationGMFRSType> createOperationGMFRS(OperationGMFRSType value) {
        return new JAXBElement<OperationGMFRSType>(_OperationGMFRS_QNAME, OperationGMFRSType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/bussines/services/", name = "requestMessage")
    public JAXBElement<RequestMessageType> createRequestMessage(RequestMessageType value) {
        return new JAXBElement<RequestMessageType>(_RequestMessage_QNAME, RequestMessageType.class, null, value);
    }

}
