//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 04:15:23 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/message/integration/services/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.bdigital.admin.messaging.services.amazonS3;
