//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 04:15:23 PM COT 
//


package co.bdigital.admin.messaging.services.amazonS3;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://nequi.co/message/integration/services/amazon}getFileRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestBodyType", propOrder = {
    "getFileRequest"
})
public class RequestBodyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://nequi.co/message/integration/services/amazon", required = true)
    protected GetFileRequestType getFileRequest;

    /**
     * Gets the value of the getFileRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetFileRequestType }
     *     
     */
    public GetFileRequestType getGetFileRequest() {
        return getFileRequest;
    }

    /**
     * Sets the value of the getFileRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetFileRequestType }
     *     
     */
    public void setGetFileRequest(GetFileRequestType value) {
        this.getFileRequest = value;
    }

}
