//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 06:27:23 PM COT 
//

package co.bdigital.cmm.messaging.esb;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for HeaderResponseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="invokerDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="destination" type="{http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB}destinationType"/&gt;
 *         &lt;element name="responseStatus" type="{http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB}ResponseStatusType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderResponseType", propOrder = { "systemId", "messageId",
        "invokerDateTime", "destination", "responseStatus" })
public class HeaderResponseType implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6695890873211619983L;

    @XmlElement(required = true)
    protected String systemId;
    @XmlElement(required = true)
    protected String messageId;
    @XmlElement(required = true)
    protected String invokerDateTime;
    @XmlElement(required = true)
    protected DestinationType destination;
    @XmlElement(required = true)
    protected ResponseStatusType responseStatus;

    /**
     * Gets the value of the systemId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the invokerDateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInvokerDateTime() {
        return invokerDateTime;
    }

    /**
     * Sets the value of the invokerDateTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInvokerDateTime(String value) {
        this.invokerDateTime = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return possible object is {@link DestinationType }
     * 
     */
    public DestinationType getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *            allowed object is {@link DestinationType }
     * 
     */
    public void setDestination(DestinationType value) {
        this.destination = value;
    }

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return possible object is {@link ResponseStatusType }
     * 
     */
    public ResponseStatusType getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *            allowed object is {@link ResponseStatusType }
     * 
     */
    public void setResponseStatus(ResponseStatusType value) {
        this.responseStatus = value;
    }

}
