//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 10:32:42 AM COT 
//


package co.bdigital.admin.messaging.services.isb.slack;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.isb.slack package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendSlackNotificationServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BancaDigital/services/SendSlackNotification", "SendSlackNotificationServiceRequest");
    private final static QName _SendSlackNotificationServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BancaDigital/services/SendSlackNotification", "SendSlackNotificationServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.isb.slack
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendSlackNotificationServiceResponseType }
     * 
     */
    public SendSlackNotificationServiceResponseType createSendSlackNotificationServiceResponseType() {
        return new SendSlackNotificationServiceResponseType();
    }

    /**
     * Create an instance of {@link SendSlackNotificationServiceRequestType }
     * 
     */
    public SendSlackNotificationServiceRequestType createSendSlackNotificationServiceRequestType() {
        return new SendSlackNotificationServiceRequestType();
    }

    /**
     * Create an instance of {@link SendSlackNotificationRSType }
     * 
     */
    public SendSlackNotificationRSType createSendSlackNotificationRSType() {
        return new SendSlackNotificationRSType();
    }

    /**
     * Create an instance of {@link SendSlackNotificationRQType }
     * 
     */
    public SendSlackNotificationRQType createSendSlackNotificationRQType() {
        return new SendSlackNotificationRQType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSlackNotificationServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BancaDigital/services/SendSlackNotification", name = "SendSlackNotificationServiceRequest")
    public JAXBElement<SendSlackNotificationServiceRequestType> createSendSlackNotificationServiceRequest(SendSlackNotificationServiceRequestType value) {
        return new JAXBElement<SendSlackNotificationServiceRequestType>(_SendSlackNotificationServiceRequest_QNAME, SendSlackNotificationServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSlackNotificationServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BancaDigital/services/SendSlackNotification", name = "SendSlackNotificationServiceResponse")
    public JAXBElement<SendSlackNotificationServiceResponseType> createSendSlackNotificationServiceResponse(SendSlackNotificationServiceResponseType value) {
        return new JAXBElement<SendSlackNotificationServiceResponseType>(_SendSlackNotificationServiceResponse_QNAME, SendSlackNotificationServiceResponseType.class, null, value);
    }

}
