//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 10:32:42 AM COT 
//


package co.bdigital.admin.messaging.services.isb.slack;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SendSlackNotificationServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SendSlackNotificationServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sendSlackNotificationRQ" type="{http://www.grupobancolombia.com/BancaDigital/services/SendSlackNotification}SendSlackNotificationRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SendSlackNotificationServiceRequestType", propOrder = {
    "sendSlackNotificationRQ"
})
public class SendSlackNotificationServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected SendSlackNotificationRQType sendSlackNotificationRQ;

    /**
     * Gets the value of the sendSlackNotificationRQ property.
     * 
     * @return
     *     possible object is
     *     {@link SendSlackNotificationRQType }
     *     
     */
    public SendSlackNotificationRQType getSendSlackNotificationRQ() {
        return sendSlackNotificationRQ;
    }

    /**
     * Sets the value of the sendSlackNotificationRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendSlackNotificationRQType }
     *     
     */
    public void setSendSlackNotificationRQ(SendSlackNotificationRQType value) {
        this.sendSlackNotificationRQ = value;
    }

}
