//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 09:50:43 AM COT 
//


package co.bdigital.admin.messaging.services.device.sendpush;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.device.sendpush package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendPushServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/SendPushService", "SendPushServiceResponse");
    private final static QName _SendPushServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/SendPushService", "SendPushServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.device.sendpush
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendPushServiceRequestType }
     * 
     */
    public SendPushServiceRequestType createSendPushServiceRequestType() {
        return new SendPushServiceRequestType();
    }

    /**
     * Create an instance of {@link SendPushServiceResponseType }
     * 
     */
    public SendPushServiceResponseType createSendPushServiceResponseType() {
        return new SendPushServiceResponseType();
    }

    /**
     * Create an instance of {@link SendPushServiceRQType }
     * 
     */
    public SendPushServiceRQType createSendPushServiceRQType() {
        return new SendPushServiceRQType();
    }

    /**
     * Create an instance of {@link SendPushServiceRSType }
     * 
     */
    public SendPushServiceRSType createSendPushServiceRSType() {
        return new SendPushServiceRSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendPushServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SendPushService", name = "SendPushServiceResponse")
    public JAXBElement<SendPushServiceResponseType> createSendPushServiceResponse(SendPushServiceResponseType value) {
        return new JAXBElement<SendPushServiceResponseType>(_SendPushServiceResponse_QNAME, SendPushServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendPushServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SendPushService", name = "SendPushServiceRequest")
    public JAXBElement<SendPushServiceRequestType> createSendPushServiceRequest(SendPushServiceRequestType value) {
        return new JAXBElement<SendPushServiceRequestType>(_SendPushServiceRequest_QNAME, SendPushServiceRequestType.class, null, value);
    }

}
