//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 09:50:43 AM COT 
//


package co.bdigital.admin.messaging.services.device.sendpush;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SendPushServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SendPushServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sendPushRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/SendPushService}SendPushServiceRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SendPushServiceRequestType", propOrder = {
    "sendPushRQ"
})
public class SendPushServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected SendPushServiceRQType sendPushRQ;

    /**
     * Gets the value of the sendPushRQ property.
     * 
     * @return
     *     possible object is
     *     {@link SendPushServiceRQType }
     *     
     */
    public SendPushServiceRQType getSendPushRQ() {
        return sendPushRQ;
    }

    /**
     * Sets the value of the sendPushRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendPushServiceRQType }
     *     
     */
    public void setSendPushRQ(SendPushServiceRQType value) {
        this.sendPushRQ = value;
    }

}
