//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 05:58:29 PM COT 
//


package co.bdigital.admin.messaging.services.createuser;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateUserServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateUserServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createUserRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/AccountServices}CreateUserRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateUserServiceRequestType", propOrder = {
    "createUserRQ"
})
public class CreateUserServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CreateUserRQType createUserRQ;

    /**
     * Gets the value of the createUserRQ property.
     * 
     * @return
     *     possible object is
     *     {@link CreateUserRQType }
     *     
     */
    public CreateUserRQType getCreateUserRQ() {
        return createUserRQ;
    }

    /**
     * Sets the value of the createUserRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateUserRQType }
     *     
     */
    public void setCreateUserRQ(CreateUserRQType value) {
        this.createUserRQ = value;
    }

}
