//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 05:58:29 PM COT 
//


package co.bdigital.admin.messaging.services.createuser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.createuser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateUserServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/AccountServices", "CreateUserServiceRequest");
    private final static QName _CreateUserServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/AccountServices", "CreateUserServiceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.createuser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateUserServiceResponseType }
     * 
     */
    public CreateUserServiceResponseType createCreateUserServiceResponseType() {
        return new CreateUserServiceResponseType();
    }

    /**
     * Create an instance of {@link CreateUserServiceRequestType }
     * 
     */
    public CreateUserServiceRequestType createCreateUserServiceRequestType() {
        return new CreateUserServiceRequestType();
    }

    /**
     * Create an instance of {@link CreateUserRQType }
     * 
     */
    public CreateUserRQType createCreateUserRQType() {
        return new CreateUserRQType();
    }

    /**
     * Create an instance of {@link CreateUserRSType }
     * 
     */
    public CreateUserRSType createCreateUserRSType() {
        return new CreateUserRSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/AccountServices", name = "CreateUserServiceRequest")
    public JAXBElement<CreateUserServiceRequestType> createCreateUserServiceRequest(CreateUserServiceRequestType value) {
        return new JAXBElement<CreateUserServiceRequestType>(_CreateUserServiceRequest_QNAME, CreateUserServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/AccountServices", name = "CreateUserServiceResponse")
    public JAXBElement<CreateUserServiceResponseType> createCreateUserServiceResponse(CreateUserServiceResponseType value) {
        return new JAXBElement<CreateUserServiceResponseType>(_CreateUserServiceResponse_QNAME, CreateUserServiceResponseType.class, null, value);
    }

}
