//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 04:58:29 PM COT 
//


package co.bdigital.admin.messaging.services.deleteuser;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.deleteuser package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeleteUserServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/UserManagementServices", "DeleteUserServiceResponse");
    private final static QName _DeleteUserServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/UserManagementServices", "DeleteUserServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.deleteuser
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteUserServiceRequestType }
     * 
     */
    public DeleteUserServiceRequestType createDeleteUserServiceRequestType() {
        return new DeleteUserServiceRequestType();
    }

    /**
     * Create an instance of {@link DeleteUserServiceResponseType }
     * 
     */
    public DeleteUserServiceResponseType createDeleteUserServiceResponseType() {
        return new DeleteUserServiceResponseType();
    }

    /**
     * Create an instance of {@link DeleteUserRSType }
     * 
     */
    public DeleteUserRSType createDeleteUserRSType() {
        return new DeleteUserRSType();
    }

    /**
     * Create an instance of {@link DeleteUserRQType }
     * 
     */
    public DeleteUserRQType createDeleteUserRQType() {
        return new DeleteUserRQType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteUserServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/UserManagementServices", name = "DeleteUserServiceResponse")
    public JAXBElement<DeleteUserServiceResponseType> createDeleteUserServiceResponse(DeleteUserServiceResponseType value) {
        return new JAXBElement<DeleteUserServiceResponseType>(_DeleteUserServiceResponse_QNAME, DeleteUserServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteUserServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/UserManagementServices", name = "DeleteUserServiceRequest")
    public JAXBElement<DeleteUserServiceRequestType> createDeleteUserServiceRequest(DeleteUserServiceRequestType value) {
        return new JAXBElement<DeleteUserServiceRequestType>(_DeleteUserServiceRequest_QNAME, DeleteUserServiceRequestType.class, null, value);
    }

}
