//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.21 at 09:09:49 AM COT 
//


package co.bdigital.cmm.messaging.slacknotification;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.mdw.acs.messaging.services.notification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SlackNotificationServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BancaDigital/services/SlackNotification", "SlackNotificationServiceResponse");
    private final static QName _SlackNotificationServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BancaDigital/services/SlackNotification", "SlackNotificationServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.mdw.acs.messaging.services.notification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SlackNotificationServiceRequestType }
     * 
     */
    public SlackNotificationServiceRequestType createSlackNotificationServiceRequestType() {
        return new SlackNotificationServiceRequestType();
    }

    /**
     * Create an instance of {@link SlackNotificationServiceResponseType }
     * 
     */
    public SlackNotificationServiceResponseType createSlackNotificationServiceResponseType() {
        return new SlackNotificationServiceResponseType();
    }

    /**
     * Create an instance of {@link SlackNotificationRQType }
     * 
     */
    public SlackNotificationRQType createSlackNotificationRQType() {
        return new SlackNotificationRQType();
    }

    /**
     * Create an instance of {@link SlackNotificationRSType }
     * 
     */
    public SlackNotificationRSType createSlackNotificationRSType() {
        return new SlackNotificationRSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlackNotificationServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BancaDigital/services/SlackNotification", name = "SlackNotificationServiceResponse")
    public JAXBElement<SlackNotificationServiceResponseType> createSlackNotificationServiceResponse(SlackNotificationServiceResponseType value) {
        return new JAXBElement<SlackNotificationServiceResponseType>(_SlackNotificationServiceResponse_QNAME, SlackNotificationServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlackNotificationServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BancaDigital/services/SlackNotification", name = "SlackNotificationServiceRequest")
    public JAXBElement<SlackNotificationServiceRequestType> createSlackNotificationServiceRequest(SlackNotificationServiceRequestType value) {
        return new JAXBElement<SlackNotificationServiceRequestType>(_SlackNotificationServiceRequest_QNAME, SlackNotificationServiceRequestType.class, null, value);
    }

}
