//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.21 at 09:09:49 AM COT 
//


package co.bdigital.cmm.messaging.slacknotification;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SlackNotificationServiceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SlackNotificationServiceResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="slackNotificationRS" type="{http://www.grupobancolombia.com/BancaDigital/services/SlackNotification}SlackNotificationRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SlackNotificationServiceResponseType", propOrder = {
    "slackNotificationRS"
})
public class SlackNotificationServiceResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected SlackNotificationRSType slackNotificationRS;

    /**
     * Gets the value of the slackNotificationRS property.
     * 
     * @return
     *     possible object is
     *     {@link SlackNotificationRSType }
     *     
     */
    public SlackNotificationRSType getSlackNotificationRS() {
        return slackNotificationRS;
    }

    /**
     * Sets the value of the slackNotificationRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SlackNotificationRSType }
     *     
     */
    public void setSlackNotificationRS(SlackNotificationRSType value) {
        this.slackNotificationRS = value;
    }

}
