//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 10:31:08 AM COT 
//


package co.bdigital.admin.messaging.validatecustomer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.validatecustomer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidateCustomerListsServiceBrokerResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", "ValidateCustomerListsServiceBrokerResponse");
    private final static QName _ValidateCustomerListsServiceBrokerRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", "ValidateCustomerListsServiceBrokerRequest");
    private final static QName _ValidateCustomerListsServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", "ValidateCustomerListsServiceResponse");
    private final static QName _ValidateCustomerListsServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", "ValidateCustomerListsServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.validatecustomer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidateCustomerListsServiceBrokerResponseType }
     * 
     */
    public ValidateCustomerListsServiceBrokerResponseType createValidateCustomerListsServiceBrokerResponseType() {
        return new ValidateCustomerListsServiceBrokerResponseType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsServiceBrokerRequestType }
     * 
     */
    public ValidateCustomerListsServiceBrokerRequestType createValidateCustomerListsServiceBrokerRequestType() {
        return new ValidateCustomerListsServiceBrokerRequestType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsServiceRequestType }
     * 
     */
    public ValidateCustomerListsServiceRequestType createValidateCustomerListsServiceRequestType() {
        return new ValidateCustomerListsServiceRequestType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsServiceResponseType }
     * 
     */
    public ValidateCustomerListsServiceResponseType createValidateCustomerListsServiceResponseType() {
        return new ValidateCustomerListsServiceResponseType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsRSType }
     * 
     */
    public ValidateCustomerListsRSType createValidateCustomerListsRSType() {
        return new ValidateCustomerListsRSType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsRQType }
     * 
     */
    public ValidateCustomerListsRQType createValidateCustomerListsRQType() {
        return new ValidateCustomerListsRQType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsBrokerRQType }
     * 
     */
    public ValidateCustomerListsBrokerRQType createValidateCustomerListsBrokerRQType() {
        return new ValidateCustomerListsBrokerRQType();
    }

    /**
     * Create an instance of {@link ValidateCustomerListsBrokerRSType }
     * 
     */
    public ValidateCustomerListsBrokerRSType createValidateCustomerListsBrokerRSType() {
        return new ValidateCustomerListsBrokerRSType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCustomerListsServiceBrokerResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", name = "ValidateCustomerListsServiceBrokerResponse")
    public JAXBElement<ValidateCustomerListsServiceBrokerResponseType> createValidateCustomerListsServiceBrokerResponse(ValidateCustomerListsServiceBrokerResponseType value) {
        return new JAXBElement<ValidateCustomerListsServiceBrokerResponseType>(_ValidateCustomerListsServiceBrokerResponse_QNAME, ValidateCustomerListsServiceBrokerResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCustomerListsServiceBrokerRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", name = "ValidateCustomerListsServiceBrokerRequest")
    public JAXBElement<ValidateCustomerListsServiceBrokerRequestType> createValidateCustomerListsServiceBrokerRequest(ValidateCustomerListsServiceBrokerRequestType value) {
        return new JAXBElement<ValidateCustomerListsServiceBrokerRequestType>(_ValidateCustomerListsServiceBrokerRequest_QNAME, ValidateCustomerListsServiceBrokerRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCustomerListsServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", name = "ValidateCustomerListsServiceResponse")
    public JAXBElement<ValidateCustomerListsServiceResponseType> createValidateCustomerListsServiceResponse(ValidateCustomerListsServiceResponseType value) {
        return new JAXBElement<ValidateCustomerListsServiceResponseType>(_ValidateCustomerListsServiceResponse_QNAME, ValidateCustomerListsServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCustomerListsServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", name = "ValidateCustomerListsServiceRequest")
    public JAXBElement<ValidateCustomerListsServiceRequestType> createValidateCustomerListsServiceRequest(ValidateCustomerListsServiceRequestType value) {
        return new JAXBElement<ValidateCustomerListsServiceRequestType>(_ValidateCustomerListsServiceRequest_QNAME, ValidateCustomerListsServiceRequestType.class, null, value);
    }

}
