//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 10:31:08 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.grupobancolombia.com/BandaDigital/services/SecurityServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.bdigital.admin.messaging.validatecustomer;
