//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 10:31:08 AM COT 
//


package co.bdigital.admin.messaging.validatecustomer;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidateCustomerListsServiceBrokerRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidateCustomerListsServiceBrokerRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validateCustomerListsBrokerRQ" type="{http://www.grupobancolombia.com/BandaDigital/services/SecurityServices}ValidateCustomerListsBrokerRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidateCustomerListsServiceBrokerRequestType", propOrder = {
    "validateCustomerListsBrokerRQ"
})
public class ValidateCustomerListsServiceBrokerRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected ValidateCustomerListsBrokerRQType validateCustomerListsBrokerRQ;

    /**
     * Gets the value of the validateCustomerListsBrokerRQ property.
     * 
     * @return
     *     possible object is
     *     {@link ValidateCustomerListsBrokerRQType }
     *     
     */
    public ValidateCustomerListsBrokerRQType getValidateCustomerListsBrokerRQ() {
        return validateCustomerListsBrokerRQ;
    }

    /**
     * Sets the value of the validateCustomerListsBrokerRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidateCustomerListsBrokerRQType }
     *     
     */
    public void setValidateCustomerListsBrokerRQ(ValidateCustomerListsBrokerRQType value) {
        this.validateCustomerListsBrokerRQ = value;
    }

}
