//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.27 at 09:59:31 AM COT 
//


package co.bdigital.admin.messaging.services.updateProfileStatus;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCustomerLocksServiceResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCustomerLocksServiceResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getCustomerLocksRS" type="{http://www.grupobancolombia.com/BandaDigital/services/GetCustomerLocksService}GetCustomerLocksRSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCustomerLocksServiceResponseType", propOrder = {
    "getCustomerLocksRS"
})
public class GetCustomerLocksServiceResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected GetCustomerLocksRSType getCustomerLocksRS;

    /**
     * Gets the value of the getCustomerLocksRS property.
     * 
     * @return
     *     possible object is
     *     {@link GetCustomerLocksRSType }
     *     
     */
    public GetCustomerLocksRSType getGetCustomerLocksRS() {
        return getCustomerLocksRS;
    }

    /**
     * Sets the value of the getCustomerLocksRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCustomerLocksRSType }
     *     
     */
    public void setGetCustomerLocksRS(GetCustomerLocksRSType value) {
        this.getCustomerLocksRS = value;
    }

}
