//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.27 at 09:59:31 AM COT 
//


package co.bdigital.admin.messaging.services.updateProfileStatus;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.bdigital.admin.messaging.services.updateProfileStatus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetCustomerLocksServiceResponse_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/GetCustomerLocksService", "GetCustomerLocksServiceResponse");
    private final static QName _GetCustomerLocksServiceRequest_QNAME = new QName("http://www.grupobancolombia.com/BandaDigital/services/GetCustomerLocksService", "GetCustomerLocksServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.bdigital.admin.messaging.services.updateProfileStatus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCustomerLocksServiceRequestType }
     * 
     */
    public GetCustomerLocksServiceRequestType createGetCustomerLocksServiceRequestType() {
        return new GetCustomerLocksServiceRequestType();
    }

    /**
     * Create an instance of {@link GetCustomerLocksServiceResponseType }
     * 
     */
    public GetCustomerLocksServiceResponseType createGetCustomerLocksServiceResponseType() {
        return new GetCustomerLocksServiceResponseType();
    }

    /**
     * Create an instance of {@link GetCustomerLocksRQType }
     * 
     */
    public GetCustomerLocksRQType createGetCustomerLocksRQType() {
        return new GetCustomerLocksRQType();
    }

    /**
     * Create an instance of {@link GetCustomerLocksRSType }
     * 
     */
    public GetCustomerLocksRSType createGetCustomerLocksRSType() {
        return new GetCustomerLocksRSType();
    }

    /**
     * Create an instance of {@link LockType }
     * 
     */
    public LockType createLockType() {
        return new LockType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerLocksServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/GetCustomerLocksService", name = "GetCustomerLocksServiceResponse")
    public JAXBElement<GetCustomerLocksServiceResponseType> createGetCustomerLocksServiceResponse(GetCustomerLocksServiceResponseType value) {
        return new JAXBElement<GetCustomerLocksServiceResponseType>(_GetCustomerLocksServiceResponse_QNAME, GetCustomerLocksServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerLocksServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.grupobancolombia.com/BandaDigital/services/GetCustomerLocksService", name = "GetCustomerLocksServiceRequest")
    public JAXBElement<GetCustomerLocksServiceRequestType> createGetCustomerLocksServiceRequest(GetCustomerLocksServiceRequestType value) {
        return new JAXBElement<GetCustomerLocksServiceRequestType>(_GetCustomerLocksServiceRequest_QNAME, GetCustomerLocksServiceRequestType.class, null, value);
    }

}
